name: Create Release Build

on: workflow_dispatch
 
jobs:
  create-release-build:

    runs-on: ubuntu-latest

    env:
      VERSION: "v2.7.0"

      - name: Checkout Constellation repository
        uses: actions/checkout@v2
        with:
          repository: constellation-app/constellation
          path: constellation

      - name: Checkout Constellation Adaptors repository
        uses: actions/checkout@v2
        with:
          repository: constellation-app/constellation-adaptors
          path: constellation-adaptors

      - name: Checkout Constellation Applications repository
        uses: actions/checkout@v2
        with:
          repository: constellation-app/constellation-applications
          path: constellation-applications

      - name: Update Version Number
        run: |
          sed -i "s/(under development)/$VERSION/" constellation/CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/startup/Startup.java

      # Cache the ivy dependencies
      - name: Restore Ivy Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy-${{ hashFiles('constellation/CoreDependencies/src/ivy.xml') }}

      - name: Create Ivy Cache
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          mkdir ~/.ivy2

      - name: Add Execute Privilege to Scripts
        run: |
          chmod +x constellation-applications/build-zip.sh
          chmod +x constellation-applications/functions.sh

      - name: Build Zips
        uses: addnab/docker-run-action@v3
        with:
          image: constellationapplication/netbeans-runner:12.0.4
          options: |
            --volume ${{ github.workspace }}:/code 
            --volume /home/runner/.ivy2:/root/.ivy2
            --workdir /code/constellation-applications
          run: |
            ./build-zip.sh -a constellation -m "constellation constellation-adaptors"

      - name: Upload Linux Build
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Linux Release Build
          path: constellation-applications/constellation/dist/constellation-linux**
          retention-days: 2

      - name: Upload MacOS Build
        uses: actions/upload-artifact@v2.3.0
        with:
          name: MacOSX Release Build
          path: constellation-applications/constellation/dist/constellation-macosx**
          retention-days: 2

      - name: Upload Windows Build
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Windows Release Build
          path: constellation-applications/constellation/dist/constellation-win**.zip
          retention-days: 2
